ASI-3371 Don't call SDK init more than once
getbread/magento-v2-bread pull request #207
Opened 2023-08-17 16:52 UTC by fkhan-bread

2023-08-17 16:54 UTC, dschoder-bread requested changes

2023-08-17 16:54 UTC, dschoder-bread commented on view/frontend/templates/breadcheckout/catalog/product/view.phtml
> +                            bread_sdk.init();
do you need a `wasSetup = true;` here?

2023-08-17 16:57 UTC, fkhan-bread commented on view/frontend/templates/breadcheckout/catalog/product/view.phtml
> +                            bread_sdk.init();
Good call. Updated

2023-08-17 16:57 UTC, dschoder-bread submitted a review, later dismissed

2023-08-21 20:24 UTC, dschoder-bread approved these changes

2023-08-21 21:28 UTC, merged